### PR TITLE
163362627 user can see updated landing page

### PR DESCRIPTION
**Pull request by sojida**
**What does this PR do?**
This PR updates landing page

**Descripton of the task**
- resize header buttons
- increase font size
- increase icon size
- add spacing to text
- increase newsletter buttons
- increase newsletter input field

**How this PR can be tested**
- clone this repo
`git pull https://github.com/sojida/politico.git`

- switch to branch
`git checkout ft-updated-landing-page-163362627`

- open (or run live server)
`UI/index.html`

**Link to relevant stories**
<a href="https://www.pivotaltracker.com/n/projects/2238870/163362627">#163362627</a>

### CODE REVIEW

**Comment by JCanaks** [comment]
Great work so far. A few feedbacks ->
- Work on the footer of the home page. Make it visible on the page
- Reduce the size of the email field in your subscribe form  and subsequently reduce the size of the form entirely.

**Comment by JCanaks** [comment]
@sojida endeavour to put screenshots on your PRs

**Comment by JCanaks** [comment]
@sojida Do a little  reduction on the overall width of the grey background on the subscribe form at the bottom of the page and the email text field width as well. Once that gone this should be good to go

**Comment by sojida** [comment]
> @sojida Do a little reduction on the overall width of the grey background on the subscribe form at the bottom of the page and the email text field width as well. Once that gone this should be good to go

- before
subscribe-before

-after 
subscribe-after

**Pull request merged**
